/* This file is generated by scripts/generate-environments.js. */

export const GIT_TAG: string | null = null;
export const GIT_COMMIT_HASH: string | null = "9d046fd70a2572b2d42db6d2d801da340e242136";
export const DEFAULT_BACKEND_ROOT: string | null = null;
export const BACKEND_TYPE: 'rest' | 'wasm' = "rest" as 'rest' | 'wasm';
