/* This file is generated by scripts/generate-environments.js. */

export const GIT_TAG: string | null = null;
export const GIT_COMMIT_HASH: string | null = "f056d0d8492ab3518e18af2dde386618eeae5b02";
export const DEFAULT_BACKEND_ROOT: string | null = null;
export const BACKEND_TYPE: 'rest' | 'wasm' = "rest" as 'rest' | 'wasm';
export type Environment = 'production' | 'development' | 'preview';
export const ENVIRONMENT: Environment = 'production';
