/* This file is generated by scripts/generate-environments.js. */

export const GIT_TAG: string | null = null;
export const GIT_COMMIT_HASH: string | null = "f11453f58d17a21799c8672436ffeca079eb6063";
export const DEFAULT_BACKEND_ROOT: string | null = null;
export const BACKEND_TYPE: 'rest' | 'wasm' = "rest" as 'rest' | 'wasm';
export type Environment = 'production' | 'development' | 'preview';
export const ENVIRONMENT: Environment = 'production';
